name: TitanMine
options:
  bundleIdPrefix: com.wolfi
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: NO
    CODE_SIGN_STYLE: Automatic

targets:
  TitanMine:
    type: application
    platform: iOS
    sources:
      - path: TitanMine
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wolfi.titanmine
        PRODUCT_NAME: TitanMine
        INFOPLIST_KEY_CFBundleDisplayName: Titan Mine
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
